### ISSUE TITLE
Out of focus when pinned to overflow menu

### ISSUE THREAD

**Issue by jupjohn** [Rayquaza01/quick-tab-switch#1] opened 2019-10-13 03:56 UTC
If you pin the extension icon to the overflow menu the keyboard shortcut will open the window but it will default to being out of focus.

Could be an easy fix, could just be the nature of Firefox rendering the overflow menu first and focusing it.

Steps:
 1. Pin the extension icon to the overflow menu
 2. Activate the QuickTabSwitch window via the keyabord shortcut

**Comment by Rayquaza01** [comment] 2019-10-14 22:49
This seems to be an issue with how Firefox handles the overflow menu. It doesn't give focus directly to popups in the overflow menu. You can focus the popup when it's in the overflow menu by pressing tab twice. The first tab puts focus on the back button above the popup, and the second one puts focus on the popup itself.

**Comment by Rayquaza01** [comment] 2023-05-31 00:28
Closing this because it seems that Firefox changed how the overflow menu works since this issue was opened. It seems to work as intended now.

**Closed by Rayquaza01** 2023-05-31 00:28 UTC
